### PR TITLE
WSCC Portable with predefined settings/favourites

### PR DESCRIPTION
**Pull request by KnifMelti**
If compiled to exe users have to go through the settings of WSCC themselves, otherwise settings/favourites are copied into the WSCC folder (.dat)
EDIT: If compiled download the settings/favourites to WSCC Portable (from KnifMelti for the moment...)

### CODE REVIEW

**Comment by KnifMelti** [comment]
Ah.. ..one could convert the **.dat-files** to **Base64** too (like your icon)...
...but, for that I don't have the skill :-)

**Comment by KnifMelti** [comment]
I close this PR of mine, it's called WiGui not AnyGui ;-)
Have my fork with in in branch plus now

**Comment by Romanitho** [comment]
Sorry I was not that active, was off ^^
It was a good idea, but in my mind it was admin tools for admin guys :) so not available by default, but I agree, finally not really necessary to "hide" it.
Regarding WSCC, I'm not big fan to implement it inside WiGui. Regarding licencing of the tool first. Then, it exists a portable and setup version. Maybe it would be better to have the setup version on the Winget Repo with proper manifest ? In this way, when needed, you could install it with WiGui 😋

for me, WiGui was built to have a GUI for WAU and to install Winget apps fast without cmd or PowerShell knowledge at all. but things change 😉

**Comment by KnifMelti** [comment]
Have implemented [Scoop ](https://scoop.sh/#/) (also on GitHub) with **Buckets** for NirSoft/SysInternals instead in my https://github.com/KnifMelti/Winget-Install-GUI/tree/plus

**Comment by Romanitho** [comment]
Scoop is another package manager like Winget or Chocolatey no ?

**Comment by KnifMelti** [comment]
> Scoop is another package manager like Winget or Chocolatey no ?

Except "../Scoop downloads and manages packages in a portable way/.. ..18587 applications and counting"...

**Comment by Romanitho** [comment]
I see. I used to have Chocolatey, but I wanted to be full MS :)

**Pull request closed without merging**
